# Makefile for TEOBResumSWrap.c

# make sure to use bash on Debian/Ubuntu, not dash
SHELL=/bin/bash

all: 
	@echo "Building python module for TEOBResumS ..."
	python setup.py build_ext --inplace

# DO NOT DELETE
