[build-system]
requires = ["setuptools>42", "numpy>=1.18"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[project]
name="teobresums-lvk"
version = '0.0.1'
authors =[{name="The TEOBResumS team", email="rossella.gamba@uni-jena.de"}]
description='TEOBResumS: Effective-One-Body model for generic compact binary coalescences'
classifiers = [
         "Programming Language :: Python :: 3",
         "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
         "Operating System :: OS Independent",
]
readme="PyREADME.md"

[project.urls]
"Homepage"="https://bitbucket.org/teobresums/teobresums/src/GIOTTO/"
"Bug Tracker"="https://bitbucket.org/teobresums/teobresums/issues?status=new&status=open&status=submitted&is_spam=!spam"
"Wiki"="https://bitbucket.org/teobresums/teobresums/wiki/Homee"
"Mailing List"="https://lserv.uni-jena.de/mailman/listinfo/teobresums"